export enum mod_slot {
    barrel = "mod_barrel",
    charge = "mod_charge",
    foregrip = "mod_foregrip",
    sight_front = "mod_sight_front",
    sight_rear = "mod_sight_rear",
    reciever = "mod_reciever",
    stock = "mod_stock",
    stock_000 = "mod_stock_000",
    magazine = "mod_magazine",
    mount = "mod_mount",
    mount_000 = "mod_mount_000",
    mount_001 = "mod_mount_001",
    mount_002 = "mod_mount_002",
    mount_003 = "mod_mount_003",
    mount_004 = "mod_mount_004",
    muzzle = "mod_muzzle",
    gas_block = "mod_gas_block",
    handguard = "mod_handguard",
    pistol_grip = "mod_pistol_grip",
    scope = "mod_scope",
    tactical = "mod_tactical",
    tactical_000 = "mod_tactical_000",
    tactical_001 = "mod_tactical_001",
    tactical_002 = "mod_tactical_002",
    tactical_003 = "mod_tactical_003"
}