"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mod_slot = void 0;
var mod_slot;
(function (mod_slot) {
    mod_slot["barrel"] = "mod_barrel";
    mod_slot["charge"] = "mod_charge";
    mod_slot["foregrip"] = "mod_foregrip";
    mod_slot["sight_front"] = "mod_sight_front";
    mod_slot["sight_rear"] = "mod_sight_rear";
    mod_slot["reciever"] = "mod_reciever";
    mod_slot["stock"] = "mod_stock";
    mod_slot["stock_000"] = "mod_stock_000";
    mod_slot["magazine"] = "mod_magazine";
    mod_slot["mount"] = "mod_mount";
    mod_slot["mount_000"] = "mod_mount_000";
    mod_slot["mount_001"] = "mod_mount_001";
    mod_slot["mount_002"] = "mod_mount_002";
    mod_slot["mount_003"] = "mod_mount_003";
    mod_slot["mount_004"] = "mod_mount_004";
    mod_slot["muzzle"] = "mod_muzzle";
    mod_slot["gas_block"] = "mod_gas_block";
    mod_slot["handguard"] = "mod_handguard";
    mod_slot["pistol_grip"] = "mod_pistol_grip";
    mod_slot["scope"] = "mod_scope";
    mod_slot["tactical"] = "mod_tactical";
    mod_slot["tactical_000"] = "mod_tactical_000";
    mod_slot["tactical_001"] = "mod_tactical_001";
    mod_slot["tactical_002"] = "mod_tactical_002";
    mod_slot["tactical_003"] = "mod_tactical_003";
})(mod_slot || (exports.mod_slot = mod_slot = {}));
//# sourceMappingURL=mod_slot.js.map